<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-U49T2LA" failures="1" tests="6" name="TestNGLearning.TestCase2" time="0.028" errors="0" timestamp="2021-02-21T22:17:47 IST" skipped="3">
  <testcase classname="TestNGLearning.TestCase2" name="multipleSoftAsserts" time="0.015"/>
  <system-out/>
  <testcase classname="TestNGLearning.TestCase2" name="isElementFound" time="0.010"/>
  <system-out/>
  <testcase classname="TestNGLearning.TestCase2" name="multipleSoftAssertsAll" time="0.003">
    <failure message="The following asserts failed:
	expected [Gmail.com] but found [Yahoo.com],
	-&gt; Forcefully failed." type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Gmail.com] but found [Yahoo.com],
-> Forcefully failed.
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestNGLearning.TestCase2.multipleSoftAssertsAll(TestCase2.java:93)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- multipleSoftAssertsAll -->
  <system-out>
<a href="D:\WorkSpace\eclipse-workspace\Selenium\screenshot\error.jpg" target="_blank">Capture Screenshot from ListenerTest.</a>  <br> <a href="D:\WorkSpace\eclipse-workspace\Selenium\screenshot\error.jpg" target="_blank"><img src="D:\WorkSpace\eclipse-workspace\Selenium\screenshot\error.jpg" height=100 width=100></a>   </system-out>
  <testcase classname="TestNGLearning.TestCase2" name="validTitle">
    <skipped/>
  </testcase> <!-- validTitle -->
  <system-out/>
  <testcase classname="TestNGLearning.TestCase2" name="forcefullyFail">
    <skipped/>
  </testcase> <!-- forcefullyFail -->
  <system-out/>
  <testcase classname="TestNGLearning.TestCase2" name="multipleAsserts">
    <skipped/>
  </testcase> <!-- multipleAsserts -->
  <system-out/>
</testsuite> <!-- TestNGLearning.TestCase2 -->
